### ISSUE TITLE
Audio does not play in firefox

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-client#138]
This is a catch all issue for FF audio bugs

Firefox PC does not work
Firefox mac does work
Firefox android does not work 
- problems 
  - mime type
    - playback 
    - `source` element filtering)
  - load state
    - FF for android never loads audio until `play()` invoked. See #160
    - FF for PC's ready state stops at 2 (rather than the three required to enable the play button atm)

Blocked by:
- [x] QutBioacoustics/baw-server#131 - mime types
- [ ] #160 - click to play
- [ ] #161 - ready state bug
