### ISSUE TITLE
Browser and platform compatibility

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-client#142]
Catch-all issue for browser and platform compatibility. General idea is to test on different browser/platform combinations, report any bugs as issues, and reference them here.
- [x] #99 - browser version check on load (status: complete)
- [x] #140 - grid lines
- [ ] #138  - audio does not play in firefox (status: issues identified, fixes pending)
- [x] #123 - chrome for android v35 (status: closed, can't reproduce, possibly solved in later version of chrome)
- [ ] #159 - iOS audio playing bug (status: fixes pending. problem: byte-range requests not sending cookie)

The spreadsheet tracking some of these issues: https://docs.google.com/spreadsheets/d/10kaio839fLPJLLw7SVZ2do1zKih5nxA1c9XZlTgbPKw/edit#gid=0
